# إعدادات SubMax الرئيسية

# عدد طلبات DNS المتزامنة. كلما زاد العدد، زادت السرعة.
concurrent_dns: 200

# المهلة القصوى بالثواني لطلبات HTTP و DNS.
timeout: 15

# فترة التوقف بالثواني في حال حدوث Rate Limit (غير مطبقة حالياً).
rate_limit_pause: 1

# أقصى عدد مرات إعادة المحاولة لطلبات API أو DNS الفاشلة (سيتم تطبيقها لاحقاً).
max_retries: 3
